Add files via upload
kit-cpp-course/korop-to pull request #1
Opened 2018-12-22 18:39 UTC by lawkeen

2018-12-24 23:15 UTC, alpatov requested changes
Честно говоря, не совсем понял какова цель приложения: это шашки или программа, автоматизирующая процесс решения судоку?

2018-12-24 23:15 UTC, alpatov commented on Cheking.cpp
> +		if (x != n)
Вложенные if-ы можно заменить одним.

2018-12-24 23:15 UTC, alpatov commented on Cheking.cpp
> +		if (x != m)
Вложенные if-ы можно заменить одним.

2018-12-24 23:15 UTC, alpatov commented on Cheking.cpp
> +	if (c == 1)
Странный код. Зачем два раза написано одно и то же?

2018-12-24 23:15 UTC, alpatov commented on Cheking.cpp
> +	if (c == 1)
Всё время забываете фигурные скобки. Или пишите в одну строчку, или ставьте скобки.

2018-12-24 23:15 UTC, alpatov commented on Cheking.cpp
> +	for (i = 0; i < count; i++)
Скобки!!!

2018-12-24 23:15 UTC, alpatov commented on Cheking.h
> +	/*CHEKING ROW FOR MATCHES*/
Комментарии не принято писать в верхнем регистре.

В верхнем регистре обозначают только разделы в больших файлах.

2018-12-24 23:15 UTC, alpatov commented on Cheking.h
> +class Cheking
К класу тоже следует добавлять пояснение в виде комментария. Поясняющего: каково назначение класса в Вашей программе.

2018-12-24 23:15 UTC, alpatov commented on DisplayReadElements.h
> +class DisplayAndRead
Документация?

2018-12-24 23:15 UTC, alpatov commented on Cheking.cpp
> +	for (x = (m / 3) * 3; x < ((m / 3) * 3 + 3); x++)
Если конструкции вложенные - обязательно ставим фигурные скобки.

2018-12-24 23:15 UTC, alpatov commented on Displaycpp.cpp
> +void DisplayAndRead::readvalues()
Слишком процедурная реализация. Можно увеличить уровень декомпозиции. Желательно с использованием ООП. Но, как вариант, для начала, можно разложить метод на вспомогательные функции.

2018-12-24 23:15 UTC, alpatov commented on Displaycpp.cpp
> +void DisplayAndRead::display()
Слишком процедурная реализация. Можно увеличить уровень декомпозиции. Желательно с использованием ООП. Но, как вариант, для начала, можно разложить метод на вспомогательные функции.

2018-12-24 23:15 UTC, alpatov commented on SudokuSolverGenerator.cpp
> +int SolveGenerate::solve()
Слишком процедурная реализация. Можно увеличить уровень декомпозиции. Желательно с использованием ООП. Но, как вариант, для начала, можно разложить метод на вспомогательные функции.

2018-12-24 23:15 UTC, alpatov commented on SudokuSolverGenerator.cpp
> +void SolveGenerate::generate()
Слишком процедурная реализация. Можно увеличить уровень декомпозиции. Желательно с использованием ООП. Но, как вариант, для начала, можно разложить метод на вспомогательные функции.

2018-12-24 23:15 UTC, alpatov commented on SudokuSolverGenerator.h
> +class SolveGenerate
Класс должен решать одну задачу. У Вас он решает две. Вывод - его нужно разделить на два класса.

Кроме этого обе задачи реализованы слишком процедурно - нужно повышать уровень декомпозиции.

2018-12-28 07:09 UTC, lawkeen reviewed
Все комментарии были учтены.

2019-01-21 18:40 UTC, closed without merging